export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESSFULL = 'LOGIN_SUCCESSFULL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESSFULL = 'LOGOUT_SUCCESSFULL';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';