export const TAGS_UPDATE= 'TAGS_UPDATE';
export const TAGS_SAVE = 'TAGS_SAVE';
export const TAGS_SAVE_SUCCESSFULL = 'TAGS_SAVE_SUCCESSFULL';
export const TAGS_SAVE_FAILURE = 'TAGS_SAVE_FAILURE';
export const TAGS_FETCH = 'TAGS_FETCH';
export const TAGS_FETCH_SUCCESSFULL = 'TAGS_FETCH_SUCCESSFULL';
export const TAGS_FETCH_FAILURE = 'TAGS_FETCH_FAILURE';