export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESSFULL = 'FETCH_USERS_SUCCESSFULL';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const EDIT_ROLE = 'EDIT_ROLE';
export const FETCH_ME = 'FETCH_ME';
export const FETCH_ME_SUCCESSFULL = 'FETCH_ME_SUCCESSFULL';
export const FETCH_ME_FAILURE = 'FETCH_ME_FAILURE';