export const NEWS_FETCH = 'NEWS_FETCH';
export const NEWS_FETCH_SUCCESSFULL = 'NEWS_FETCH_SUCCESSFULL';
export const NEWS_FETCH_FAILURE = 'NEWS_FETCH_FAILURE';
export const NEWS_CREATE = 'NEWS_CREATE';
export const NEWS_UPDATE = 'NEWS_UPDATE';